name: CI

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+'  # matches to backport branches, e.g. 3.6
    tags: [ 'v*' ]
  pull_request:
    branches:
      - 'master'
      - '[0-9].[0-9]+'
  schedule:
    - cron:  '0 6 * * *'  # Daily 6AM UTC build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:
  # TODO: replace to @master after the PR merging
  lint:
    name: Lint
    uses: aio-libs/aiohttp/.github/workflows/lint.yml@f4d13de656c875dca8662f2772da844d4d9a553a
  test:
    name: Test
    needs: lint
    uses: aio-libs/aiohttp/.github/workflows/test.yml@f4d13de656c875dca8662f2772da844d4d9a553a

  check:  # This job does nothing and is only used for the branch protection
    needs:
    - test

    runs-on: ubuntu-latest

    steps:
      - name: Report success of the test matrix
        run: >-
          print("All's good")
        shell: python

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: check
    # Run only on pushing a tag
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses:
      uses: aio-libs/aiohttp/.github/workflows/deploy.yml@master
