name: Compile dependencies
on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to use'
        default: ''
        required: false
        type: string
    secrets:
      GITHUB_TOKEN:
        description: 'Github token'
        required: true

jobs:
  post-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Cache PyPI
      uses: actions/cache@v2.1.6
      with:
        key: post-update-${{ hashFiles('requirements/*.txt') }}
        path: ~/.cache/pip
        restore-keys: |
            post-update-
    - name: Update pip, wheel, setuptools
      run: |
        python -m pip install -U pip wheel setuptools
    - name: Install dependencies
      run: |
        python -m pip install -r requirements/pip-tools.txt -c requirements/constraints.txt
    - name: Run pip-compile
      run: |
        make compile-deps
    - name: Check if compiled deps are changed
      id: meta
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "::set-output name=changed::true"
        else
          echo "::set-output name=changed::false"
    - name: Commit and push if needed\
      if: ${{ steps.meta.values.changed == 'true' }}
      run: |
        # Cleanup workspace
        rm -rf ${{ github.workspace }}
        # Checkout with read-write access
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        gh pr checkout ${{ github.event.pull_request.number }}
        # Regenerate dependencies again
        make compile-deps
        # push regenerated dependencies back to GitHub PR
        git add requirements/constraints.txt
        git commit -m "Update constraints"
        git push
