name: Cron

on:
  schedule:
    - cron:  '0 6 * * *'  # Daily 6AM UTC build

env:
  REF: master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  # No compile-deps on cron job.
  # TODO: Apply run to all active branches by keeping workflows like cron-39.yml etc.

  lint:
    name: Lint
    uses: aio-libs/aiohttp/.github/workflows/sub-lint.yml@master
    with:
      ref: master
  test:
    name: Test
    uses: aio-libs/aiohttp/.github/workflows/sub-test.yml@master
    with:
      ref: master
