name: Push

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+'  # matches to backport branches, e.g. 3.6

# Use default concurrency, don't want cancelling commit checks on master/backports
# anyway

jobs:
  # NB: No compile-deps on push, if the recompilation is needed it should be done
  # explicitly by a separate commit to master or backport branches

  lint:
    name: Lint
    uses: aio-libs/aiohttp/.github/workflows/lint.yml@master
  test:
    name: Test
    uses: aio-libs/aiohttp/.github/workflows/test.yml@master

  check:  # This job does nothing and is only used for the branch protection
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Report success of the test matrix
        run: >-
          print("All's good")
        shell: python
