name: Update

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+'  # matches to backport branches, e.g. 3.6
    tags: [ 'v*' ]

# Use default concurrency, don't want cancelling commit checks on master/backports
# anyway

jobs:
  # NB: No compile-deps on push, if recompilation is needed it should be done
  # explicitly by a separate commit to master or backport branches

  # TODO: replace to @master after the PR merging
  lint:
    name: Lint
    uses: aio-libs/aiohttp/.github/workflows/lint.yml@f4d13de656c875dca8662f2772da844d4d9a553a
  test:
    name: Test
    needs: lint
    uses: aio-libs/aiohttp/.github/workflows/test.yml@f4d13de656c875dca8662f2772da844d4d9a553a

  check:  # This job does nothing and is only used for the branch protection
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Report success of the test matrix
        run: >-
          print("All's good")
        shell: python

  deploy:
    name: Deploy
    needs: check
    # Run only on pushing a tag
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: aio-libs/aiohttp/.github/workflows/deploy.yml@f4d13de656c875dca8662f2772da844d4d9a553a
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
