name: Compile dependencies
on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to use'
        default: ''
        required: false
        type: string
    secrets:
      GITHUB_TOKEN:
        description: 'Github token'
        required: true

jobs:
  post-update:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    - name: Checkout
      run: |
        gh pr checkout ${{ github.event.pull_request.number }}
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Cache PyPI
      uses: actions/cache@v2.1.7
      with:
        key: post-update
        path: ~/.cache/pip
        restore-keys: |
            post-update-
    - name: Update pip-tools
      run: |
        python -m pip install -U pip-tools
    - name: Run pip-compile
      run: |
        make compile-deps
    - name: Commit and push if needed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Recompile requirements/constraints.txt
